name: Docker Image CI

on:
  release:
    types: [published]

env:
  DOCKERHUB_SYSTEM_IMAGE: 'crazyher/campus-surveillance-system'
  DOCKERHUB_AI_IMAGE: 'crazyher/campus-surveillance-ai-end'
  NODE_VERSION: '18.x'

jobs:
  Build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Lint & build
        run: |
          npm i -g pnpm
          cd frontend
          pnpm install
          pnpm run lint
          pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: ./frontend/dist

  Build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Lint & build
        run: |
          npm i -g pnpm
          cd backend
          pnpm install
          pnpm run lint
          pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: ./backend/dist

  Build-docker-for-frontend-and-backend:
    runs-on: ubuntu-latest
    needs: [Build-frontend, Build-backend]
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact from frontend build job
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: ./frontend/dist

      - name: Download artifact from backend build job
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: ./backend/dist

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ${{ env.DOCKERHUB_SYSTEM_IMAGE }}:latest
          context: .
          file: ./front-backend.Dockerfile

  Build-docker-for-ai-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ${{ env.DOCKERHUB_AI_IMAGE }}:latest
          context: .
          file: ./ai-end.Dockerfile
